#!/bin/bash

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


after_install() {
    touch "__INSTALL_3DIGIT__"/desktop/conf/.not_configured_yet

    # Init symlinks for missing libraries
    for LIB in "__INSTALL_3DIGIT__"/ext/libcompat/*; do
        LIBNAME=$(basename $LIB)
        if ! ldconfig -p | grep -q "$LIBNAME "; then
            . "$LIB"
            for LIB_PATH in $LIB_LOOKUP_PATH; do
                if [ -e "$LIB_PATH" ] && [ ! -e "__INSTALL_3DIGIT__/build/env/lib/${LIBNAME}" ]; then
                    ln -sf "$LIB_PATH" "__INSTALL_3DIGIT__/build/env/lib/${LIBNAME}"
                    break
                fi
            done
            unset LIB_LOOKUP_PATH
        fi
    done

    # Init configuration files from templates
    for CONF in "__INSTALL_3DIGIT__"/desktop/conf.dist/* ; do
        CONFNAME=$(basename $CONF)
        if [ ! -e "__INSTALL_3DIGIT__"/desktop/conf/$CONFNAME ] ; then
            cp -Rp $CONF "__INSTALL_3DIGIT__"/desktop/conf/$CONFNAME
        fi
    done
}

after_upgrade() {
    OLD_TIMESTAMP=$1
    OLD_VERSION=$(echo "$OLD_TIMESTAMP" | grep -o '^[0-9]*\.[0-9]*\.[0-9]*')

    #
    # Remove directory with old version
    #
    NEW_VERSION=$(cat __PREFIX__/hue/hueversion)

    if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
        rm -rf "__PREFIX__/hue/hue-${OLD_VERSION}"
    fi
}


case "$1" in
    configure)
        after_install
        if [ -n "$2" ] ; then
            after_upgrade "$2"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
