#!/bin/sh

. "${MAPR_HOME}/conf/env.sh"

# Add path to libjvm.so into LD_LIBRARY_PATH
# Find JRE directory using MapR env.sh script
if [ -e "${JAVA_HOME}/jre/lib/amd64/server" ]; then
    # java_directory points to JDK
    libjvm_path="${JAVA_HOME}/jre/lib/amd64/server"
elif [ -e "${JAVA_HOME}/lib/amd64/server" ]; then
    # java_directory points to JRE (MapR env.sh can return JAVA_HOME pointing to JRE_HOME)
    libjvm_path="${JAVA_HOME}/lib/amd64/server"
elif [ -e "${JAVA_HOME}/lib/server" ]; then
    # Java 11
    libjvm_path="${JAVA_HOME}/lib/server"
fi
export LD_LIBRARY_PATH="${MAPR_HOME}/lib:${HUE_HOME}/build/env/lib:${libjvm_path}:${LD_LIBRARY_PATH}"

# Add /opt/mapr/libexp/maprsecurity.so into PYTHONPATH
export PYTHONPATH="${MAPR_HOME}/libexp:${PYTHONPATH}"

# Explicitly set location of cyrus-sasl libraries when we package them
if [ -d "${HUE_HOME}/build/env/lib/sasl2" ]; then
    export SASL_PATH="${HUE_HOME}/build/env/lib/sasl2"
fi
